In [2]:
import numpy as np

numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

print(numbers1)
print(numbers2)

[99 51 93 30 54 83]
[78 51 15 58 73 74]


In [3]:
result = numbers1 + numbers2
print(result)
result = numbers1 + 10
print(result)
result = numbers1 - numbers2
print(result)
result = numbers1 - 10
print(result)
result = numbers1 * numbers2
print(result)
result = numbers1 * 10
print(result)
result = numbers1 / numbers2
print(result)
result = numbers1 / 10
print(result)

[177 102 108  88 127 157]
[109  61 103  40  64  93]
[ 21   0  78 -28 -19   9]
[89 41 83 20 44 73]
[7722 2601 1395 1740 3942 6142]
[990 510 930 300 540 830]
[1.26923077 1.         6.2        0.51724138 0.73972603 1.12162162]
[9.9 5.1 9.3 3.  5.4 8.3]


In [4]:
result = np.sin(numbers1)
print(result)
result = np.cos(numbers1) 
print(result)
result = np.sqrt(numbers1) # kök alma
print(result)
result = np.log(numbers1) # log alma
print(result)

[-0.99920683  0.67022918 -0.94828214 -0.98803162 -0.55878905  0.96836446]
[ 0.03982088  0.7421542   0.3174287   0.15425145 -0.82930983  0.24954012]
[9.94987437 7.14142843 9.64365076 5.47722558 7.34846923 9.11043358]
[4.59511985 3.93182563 4.53259949 3.40119738 3.98898405 4.41884061]


In [5]:
mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)

print(mnumbers1)
print(mnumbers2)

[[99 51 93]
 [30 54 83]]
[[78 51 15]
 [58 73 74]]


In [6]:
result = np.vstack((mnumbers1,mnumbers2)) #2. arrayı 1. arraya sütun boyunca ekler
print(result)
result = np.hstack((mnumbers1,mnumbers2)) #2. arrayı 1. arraya satır boyunca ekler
print(result)

[[99 51 93]
 [30 54 83]
 [78 51 15]
 [58 73 74]]
[[99 51 93 78 51 15]
 [30 54 83 58 73 74]]


In [10]:
result = numbers1 >= 50
print(result)
print(numbers1[result])
result = numbers1 % 2 == 0
print(result)
print(numbers1[result])

[ True  True  True False  True  True]
[99 51 93 54 83]
[False False False  True  True False]
[30 54]
