In [5]:
import numpy as np
result = np.array([1,3,5,7,9])
print(result)


[1 3 5 7 9]


In [8]:
result = np.arange(1,10)
print(result)
result = np.arange(10,100,3)
print(result)

[1 2 3 4 5 6 7 8 9]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [9]:
result = np.zeros(10)
print(result)
result = np.ones(10)
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Belirtilen aralıktaki sayıları eşit parçalara bölme

In [11]:
result = np.linspace(0,100,5)
print(result)
result = np.linspace(0,5,5)
print(result)

[  0.  25.  50.  75. 100.]
[0.   1.25 2.5  3.75 5.  ]


### Belirtilen aralık için sayı oluşturma

In [14]:
result = np.random.randint(0,10)
print(result)
result = np.random.randint(20)
print(result)
result = np.random.randint(1,10,3)
print(result)

6
11
[9 4 4]


### 0 - 1 arasında rasgele sayı oluşturma

In [15]:
result = np.random.rand(5)
print(result)
result = np.random.randn(5)
print(result)

[0.9797924  0.39002943 0.54438883 0.21437798 0.29089281]
[-0.3085282  -0.46731248  1.91377412 -1.01234416 -0.09982344]


In [ ]:
np_array = np.arange(50)
np_multi = np_array.reshape(5,10)
print(np_multi.sum(axis=1)) # Satırların ortalaması
print(np_multi.sum(axis=0)) # Sütunların ortalaması

In [16]:
rnd_numbers = np.random.randint(1,100,10)
print(rnd_numbers)
result = rnd_numbers.max() #En büyük sayı
print(result)
result = rnd_numbers.min() #En küçük sayı
print(result)
result = rnd_numbers.mean() #Ortalaması
print(result)
result = rnd_numbers.argmax() #En büyük sayının indexi
print(result)
result = rnd_numbers.argmin() #En küçük sayının indexi
print(result)

[48 88 51 58 12  7 87 56 58 26]
88
7
49.1
1
5
