In [1]:
import numpy as np

numbers = np.array([0,5,10,15,20,25,50,75])

### TEK BOYUTLU ARRAY İÇİN

In [10]:
result = numbers[5]
print(result)
result = numbers[-1]
print(result)
result = numbers[0:3]
print(result)
result = numbers[:3]
print(result)
result = numbers[3:]
print(result)
result = numbers[::] # ---> [başlangıç sayısı : son sayı(dahil değil) : artış miktarı] !!!index olarak yazılır.
print(result)
result = numbers[::-1]
print(result)
result = numbers[:]
print(result)

25
75
[ 0  5 10]
[ 0  5 10]
[15 20 25 50 75]
[ 0  5 10 15 20 25 50 75]
[75 50 25 20 15 10  5  0]
[ 0  5 10 15 20 25 50 75]


### 2 BOYUTLU ARRAY İÇİN

In [11]:
numbers2 = np.array([[0,5,10],[15,20,25],[50,75,85]])
result = numbers2[0]
result = numbers2[2]
result = numbers2[0,2]
result = numbers2[2,1]
result = numbers2[:,2]
result = numbers2[:,0]
result = numbers2[:,0:2]
result = numbers2[-1,:]
result = numbers2[:2,:2]

In [18]:
# Aynı bellek konumu kullanılıyor
arr1 = np.arange(0,10)
arr2 = arr1 # referans

arr2[0] = 20

print(arr1)
print(arr2)

print("*******************************")

# Farklı bellek konumu kullanılıyor
arr1 = np.arange(0,10)
arr2 = arr1.copy()

arr2[0] = 20

print(arr1)
print(arr2)


[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]
*******************************
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
